In [1]:
import os
from dotenv import load_dotenv
import boto3
import pandas as pd
from io import BytesIO

In [2]:
load_dotenv()

True

In [3]:
S3_KEY_ID = os.getenv("S3_KEY_ID")
S3_SECRET = os.getenv("S3_SECRET")
S3_ENDPOINT = os.getenv("S3_ENDPOINT")
S3_BUCKET = os.getenv("S3_BUCKET")

In [4]:
s3 = boto3.client(
    "s3",
    endpoint_url=S3_ENDPOINT,
    aws_access_key_id=S3_KEY_ID,
    aws_secret_access_key=S3_SECRET
)

In [5]:
response = s3.list_objects_v2(Bucket=S3_BUCKET)

files = [obj["Key"] for obj in response.get("Contents", [])]
files

['currencies_history.csv',
 'transactions_batch_1.csv',
 'transactions_batch_10.csv',
 'transactions_batch_2.csv',
 'transactions_batch_3.csv',
 'transactions_batch_4.csv',
 'transactions_batch_5.csv',
 'transactions_batch_6.csv',
 'transactions_batch_7.csv',
 'transactions_batch_8.csv',
 'transactions_batch_9.csv']

In [6]:
currencies_history = "currencies_history.csv"
transactions_batch = "transactions_batch_1.csv"

currencies = pd.read_csv(BytesIO(s3.get_object(Bucket=S3_BUCKET, Key=currencies_history)["Body"].read()))
transactions = pd.read_csv(BytesIO(s3.get_object(Bucket=S3_BUCKET, Key=transactions_batch)["Body"].read()))

In [7]:
currencies

      currency_code  currency_code_with date_update  currency_with_div
0               430                 470  2022-10-01               0.92
1               430                 460  2022-10-01               0.95
2               430                 450  2022-10-01               1.08
3               430                 410  2022-10-01               1.02
4               430                 420  2022-10-01               1.05
...             ...                 ...         ...                ...
1675            440                 470  2022-11-09               0.96
1676            440                 460  2022-11-09               1.09
1677            440                 450  2022-11-09               0.98
1678            440                 410  2022-11-09               0.92
1679            440                 420  2022-11-09               0.99

[1680 rows x 4 columns]

In [8]:
transactions

,operation_id,account_number_from,account_number_to,currency_code,country,status,transaction_type,amount,transaction_dt
0,7f9922e8-48b8-4097-9ff6-3eab131e80d9,914810,4454155,430,russia,queued,sbp_incoming,230900,2022-10-01 00:00:02
1,e8793d0b-a562-4bcf-8c04-155792f3ec93,914810,5371058,430,russia,queued,sbp_incoming,62000,2022-10-01 00:00:02
2,2e5f9d2e-2798-4527-a416-69b2f87c7289,914810,6633598,470,turkey,queued,sbp_incoming,30000,2022-10-01 00:00:04
3,b83232d1-b194-48e9-b361-ec7cc7326ce5,903810,1027227,430,russia,queued,c2b_partner_incoming,100000,2022-10-01 00:00:06
4,cb5ba138-55bc-415b-81e2-ee8c5b89f444,903810,3934590,470,turkey,queued,sbp_incoming,75000,2022-10-01 00:00:06
...,...,...,...,...,...,...,...,...,...
113544,a68b0e5a-946c-4b47-a550-cf315ccf34a6,914810,9532605,440,italy,queued,c2a_incoming,200000,2022-10-01 14:30:54
113545,f757577b-95ef-4186-a31b-5251e6e10bdc,914810,9495772,460,england,queued,authorization,-7500,2022-10-01 14:30:54
113546,78d1f55f-35b1-4a26-b4a6-97fba48e000e,914810,3471288,410,canada,queued,sbp_outgoing,-223500,2022-10-01 14:30:54
113547,2ad33a5b-d545-4d25-aa27-8c72ffcf6371,903810,1346959,430,russia,done,sbp_incoming,100000,2022-10-01 14:30:54
113548,5d9c2c05-466f-4b76-8fea-674f4a215acb,903810,2440793,450,china,queued,c2b_partner_incoming,200000,2022-10-01 14:30:54

In [9]:
currencies.columns

Index(['currency_code', 'currency_code_with', 'date_update',
       'currency_with_div'],
      dtype='object')

In [10]:
transactions.columns

Index(['operation_id', 'account_number_from', 'account_number_to',
       'currency_code', 'country', 'status', 'transaction_type', 'amount',
       'transaction_dt'],
      dtype='object')

In [11]:
transactions["amount"].min(), transactions["amount"].max()

(np.int64(-6554000), np.int64(12200000))